In [1]:
import torch

In [4]:
x = torch.ones([2,3])
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [6]:
torch.range(1, 3, 0.5)

/home/imed002/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  """Entry point for launching an IPython kernel.


tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000])

In [7]:
torch.arange(1, 6, 2)

tensor([1, 3, 5])

In [8]:
torch.range(1,6,2)

/home/imed002/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  """Entry point for launching an IPython kernel.


tensor([1., 3., 5.])

In [9]:
torch.linspace(1,3,5)

tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000])

In [10]:
torch.logspace(start=0, end=10, steps=5)

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [13]:
1.000e-10

1e-10

In [14]:
torch.linspace(start=0.1, end=1.0, steps=5)

tensor([0.1000, 0.3250, 0.5500, 0.7750, 1.0000])

In [15]:
torch.logspace(start=0.1, end=1.0, steps=5)

tensor([ 1.2589,  2.1135,  3.5481,  5.9566, 10.0000])

In [16]:
torch.linspace(start=-10, end=10, steps=5)

tensor([-10.,  -5.,   0.,   5.,  10.])

In [17]:
1e-2

0.01

In [18]:
torch.empty(2, 3)

tensor([[2.8905e+17, 4.5755e-41, 7.1251e-37],
        [0.0000e+00, 1.0000e+01, 6.7008e+26]])

In [19]:
torch.empty((2,3))

tensor([[ 2.8905e+17,  4.5755e-41,  7.0189e-37],
        [ 0.0000e+00, -5.0309e-15,  4.5754e-41]])

In [2]:
import torch.nn as nn
import torch.nn.functional as F

class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.conv1 = nn.Conv2d(1, 20, 5)
        self.conv2 = nn.Conv2d(20, 20, 5)
        self.m=7

    def forward(self, x):
        x = F.relu(self.conv1(x))
        return F.relu(self.conv2(x))

In [3]:
model = Model()
print(model)

Model(
  (conv1): Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(20, 20, kernel_size=(5, 5), stride=(1, 1))
)


In [4]:
print(model.named_parameters())

<generator object Module.named_parameters at 0x7ff112737e08>


In [5]:
for name, param in model.named_parameters():
    print(name, param)

conv1.weight Parameter containing:
tensor([[[[ 0.0394,  0.1183,  0.0404,  0.0466, -0.1278],
          [ 0.0209, -0.1498,  0.1778,  0.0529,  0.1875],
          [ 0.0095,  0.1137,  0.0410, -0.1295,  0.1362],
          [-0.0155,  0.1802,  0.1596,  0.1889,  0.0738],
          [ 0.1277,  0.0356,  0.1944, -0.0185, -0.1121]]],


        [[[ 0.0274, -0.0331,  0.1584,  0.1449,  0.1167],
          [-0.0069,  0.0912,  0.1523,  0.0521, -0.1307],
          [-0.1176,  0.0782,  0.0792, -0.0911, -0.1206],
          [ 0.1119,  0.1263,  0.1983,  0.1738,  0.1695],
          [-0.0736,  0.0241, -0.0864, -0.0335, -0.1367]]],


        [[[ 0.0969,  0.0596, -0.1285,  0.0572, -0.1279],
          [-0.0479,  0.0932,  0.1674,  0.0019,  0.1175],
          [ 0.0065, -0.1904,  0.1957,  0.1565, -0.1305],
          [-0.0580,  0.0888,  0.0162,  0.0041, -0.0387],
          [ 0.1731, -0.1264, -0.1941, -0.1127, -0.1425]]],


        [[[-0.1753, -0.1312, -0.1663, -0.0318, -0.1262],
          [-0.1822,  0.1099, -0.1566, -0.

In [6]:
print(len(list(model.named_parameters())))

4


In [7]:
class MyModule(nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()
        self.linears = nn.ModuleList([nn.Linear(10, 10) for i in range(10)])

    def forward(self, x):
        # ModuleList can act as an iterable, or be indexed using ints
        for i, l in enumerate(self.linears):
            x = self.linears[i // 2](x) + l(x)
        return x

In [8]:
mymodule = MyModule()
print(mymodule)

MyModule(
  (linears): ModuleList(
    (0): Linear(in_features=10, out_features=10, bias=True)
    (1): Linear(in_features=10, out_features=10, bias=True)
    (2): Linear(in_features=10, out_features=10, bias=True)
    (3): Linear(in_features=10, out_features=10, bias=True)
    (4): Linear(in_features=10, out_features=10, bias=True)
    (5): Linear(in_features=10, out_features=10, bias=True)
    (6): Linear(in_features=10, out_features=10, bias=True)
    (7): Linear(in_features=10, out_features=10, bias=True)
    (8): Linear(in_features=10, out_features=10, bias=True)
    (9): Linear(in_features=10, out_features=10, bias=True)
  )
)


In [9]:
print(list(mymodule.named_parameters()))

[('linears.0.weight', Parameter containing:
tensor([[ 0.0826, -0.1772, -0.2045,  0.0265, -0.1212,  0.1401,  0.2145, -0.0624,
          0.0938, -0.1433],
        [ 0.0155, -0.1873,  0.2547,  0.2467,  0.0743, -0.0941, -0.0669, -0.2242,
         -0.2258,  0.3107],
        [ 0.1200,  0.0648, -0.2330,  0.2822, -0.1627,  0.2759, -0.1721,  0.2964,
         -0.3037, -0.1022],
        [ 0.0094,  0.1305,  0.2244, -0.0355,  0.3112,  0.2498, -0.2094, -0.1934,
         -0.2905,  0.0582],
        [ 0.0528, -0.2741, -0.1509, -0.0699, -0.1693,  0.1527, -0.0099, -0.0213,
         -0.1596, -0.1991],
        [-0.0175,  0.0389, -0.0006,  0.0933,  0.2374, -0.2930,  0.0676, -0.0487,
         -0.0784, -0.2659],
        [-0.1923, -0.2190, -0.0936, -0.2170,  0.1129,  0.0252, -0.0170, -0.3151,
          0.0194,  0.0814],
        [ 0.2153, -0.1190,  0.1290,  0.2056, -0.0853,  0.0047, -0.1273, -0.2586,
         -0.1937, -0.0550],
        [-0.3118,  0.2745, -0.1377,  0.0582,  0.1189, -0.2947, -0.0088, -0.2865,
   

In [10]:
M = nn.Sequential(
          nn.Conv2d(1,20,5),
          nn.ReLU(),
          nn.Conv2d(20,64,5),
          nn.ReLU()
        )

In [11]:
print(M)

Sequential(
  (0): Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU()
  (2): Conv2d(20, 64, kernel_size=(5, 5), stride=(1, 1))
  (3): ReLU()
)


In [12]:
linears = nn.ModuleList([nn.Linear(10, 10) for i in range(10)])

In [13]:
print(linears)

ModuleList(
  (0): Linear(in_features=10, out_features=10, bias=True)
  (1): Linear(in_features=10, out_features=10, bias=True)
  (2): Linear(in_features=10, out_features=10, bias=True)
  (3): Linear(in_features=10, out_features=10, bias=True)
  (4): Linear(in_features=10, out_features=10, bias=True)
  (5): Linear(in_features=10, out_features=10, bias=True)
  (6): Linear(in_features=10, out_features=10, bias=True)
  (7): Linear(in_features=10, out_features=10, bias=True)
  (8): Linear(in_features=10, out_features=10, bias=True)
  (9): Linear(in_features=10, out_features=10, bias=True)
)


In [22]:
class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 5x5 square convolution kernel
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)

        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
        self.bn = nn.BatchNorm2d(10)
        self.relu = nn.ReLU()
        self.mse_loss = nn.MSELoss()
        self.bceloss = nn.BCEWithLogitsLoss()

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))

        # 2 is ame as (2, 2)
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)

        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)

        return x

In [23]:
net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
  (bn): BatchNorm2d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU()
  (mse_loss): MSELoss()
  (bceloss): BCEWithLogitsLoss()
)


In [30]:
print(net.conv1.weight.requires_grad)

True


In [27]:
print(net.state_dict())

OrderedDict([('conv1.weight', tensor([[[[-0.1943, -0.0071, -0.1956,  0.0704, -0.0566],
          [-0.0127, -0.1863, -0.1984, -0.1939,  0.1696],
          [ 0.1047,  0.1310,  0.1467,  0.1615, -0.0367],
          [-0.0207,  0.0642,  0.1347,  0.1665, -0.0679],
          [-0.0648, -0.0072, -0.1231, -0.0035,  0.1412]]],


        [[[ 0.1445, -0.1416, -0.1929,  0.1382,  0.0215],
          [ 0.0331, -0.1842,  0.0085,  0.1060,  0.0577],
          [-0.1264, -0.1531,  0.0306,  0.1372, -0.1785],
          [ 0.0177, -0.1545, -0.1378,  0.1881,  0.1373],
          [-0.1755,  0.0136,  0.1844, -0.0865,  0.1212]]],


        [[[-0.1047,  0.0148,  0.0402, -0.0234, -0.0512],
          [-0.1750, -0.0859,  0.1094, -0.1391,  0.0568],
          [ 0.0020,  0.1397,  0.1930,  0.1701,  0.1783],
          [-0.1931, -0.0377,  0.0355,  0.0609,  0.0714],
          [ 0.1101, -0.0106,  0.0969,  0.0724,  0.1942]]],


        [[[-0.0538, -0.1354,  0.1199,  0.0510, -0.0590],
          [-0.1720, -0.0286,  0.0747,  0.0580,

In [29]:
import torch
pos_weight = torch.ones([64])
net.bceloss = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
print(net.state_dict())

OrderedDict([('conv1.weight', tensor([[[[-0.1943, -0.0071, -0.1956,  0.0704, -0.0566],
          [-0.0127, -0.1863, -0.1984, -0.1939,  0.1696],
          [ 0.1047,  0.1310,  0.1467,  0.1615, -0.0367],
          [-0.0207,  0.0642,  0.1347,  0.1665, -0.0679],
          [-0.0648, -0.0072, -0.1231, -0.0035,  0.1412]]],


        [[[ 0.1445, -0.1416, -0.1929,  0.1382,  0.0215],
          [ 0.0331, -0.1842,  0.0085,  0.1060,  0.0577],
          [-0.1264, -0.1531,  0.0306,  0.1372, -0.1785],
          [ 0.0177, -0.1545, -0.1378,  0.1881,  0.1373],
          [-0.1755,  0.0136,  0.1844, -0.0865,  0.1212]]],


        [[[-0.1047,  0.0148,  0.0402, -0.0234, -0.0512],
          [-0.1750, -0.0859,  0.1094, -0.1391,  0.0568],
          [ 0.0020,  0.1397,  0.1930,  0.1701,  0.1783],
          [-0.1931, -0.0377,  0.0355,  0.0609,  0.0714],
          [ 0.1101, -0.0106,  0.0969,  0.0724,  0.1942]]],


        [[[-0.0538, -0.1354,  0.1199,  0.0510, -0.0590],
          [-0.1720, -0.0286,  0.0747,  0.0580,

In [25]:
for name,param in net.named_parameters():
    print(name, len(param))

conv1.weight 6
conv1.bias 6
conv2.weight 16
conv2.bias 16
fc1.weight 120
fc1.bias 120
fc2.weight 84
fc2.bias 84
fc3.weight 10
fc3.bias 10
bn.weight 10
bn.bias 10


In [26]:
for name,param in net.named_parameters():
    print(name, param)

conv1.weight Parameter containing:
tensor([[[[-0.1943, -0.0071, -0.1956,  0.0704, -0.0566],
          [-0.0127, -0.1863, -0.1984, -0.1939,  0.1696],
          [ 0.1047,  0.1310,  0.1467,  0.1615, -0.0367],
          [-0.0207,  0.0642,  0.1347,  0.1665, -0.0679],
          [-0.0648, -0.0072, -0.1231, -0.0035,  0.1412]]],


        [[[ 0.1445, -0.1416, -0.1929,  0.1382,  0.0215],
          [ 0.0331, -0.1842,  0.0085,  0.1060,  0.0577],
          [-0.1264, -0.1531,  0.0306,  0.1372, -0.1785],
          [ 0.0177, -0.1545, -0.1378,  0.1881,  0.1373],
          [-0.1755,  0.0136,  0.1844, -0.0865,  0.1212]]],


        [[[-0.1047,  0.0148,  0.0402, -0.0234, -0.0512],
          [-0.1750, -0.0859,  0.1094, -0.1391,  0.0568],
          [ 0.0020,  0.1397,  0.1930,  0.1701,  0.1783],
          [-0.1931, -0.0377,  0.0355,  0.0609,  0.0714],
          [ 0.1101, -0.0106,  0.0969,  0.0724,  0.1942]]],


        [[[-0.0538, -0.1354,  0.1199,  0.0510, -0.0590],
          [-0.1720, -0.0286,  0.0747,  0.

In [51]:
print(net.children())

<generator object Module.children at 0x7fb72818f0f8>


In [52]:
for i in net.children():
    print(i)

Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
Linear(in_features=400, out_features=120, bias=True)
Linear(in_features=120, out_features=84, bias=True)
Linear(in_features=84, out_features=10, bias=True)
BatchNorm2d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
ReLU()
MSELoss()


In [57]:
for i in net.fc1.parameters():
    print(i)

Parameter containing:
tensor([[ 0.0110,  0.0115, -0.0353,  ...,  0.0187, -0.0176, -0.0454],
        [ 0.0075,  0.0372,  0.0326,  ...,  0.0487, -0.0256, -0.0316],
        [ 0.0264, -0.0275, -0.0129,  ..., -0.0255, -0.0461,  0.0007],
        ...,
        [ 0.0043,  0.0275,  0.0327,  ..., -0.0291,  0.0333,  0.0113],
        [-0.0216,  0.0466,  0.0245,  ...,  0.0082, -0.0371,  0.0134],
        [-0.0376,  0.0331,  0.0463,  ...,  0.0110,  0.0349, -0.0401]],
       requires_grad=True)
Parameter containing:
tensor([-0.0103, -0.0179,  0.0075,  0.0146, -0.0492, -0.0196, -0.0166, -0.0122,
         0.0495, -0.0326,  0.0242,  0.0105, -0.0071, -0.0309,  0.0240, -0.0335,
        -0.0219, -0.0285,  0.0229, -0.0172, -0.0236, -0.0055, -0.0044, -0.0467,
        -0.0140, -0.0392, -0.0473,  0.0349,  0.0118, -0.0092, -0.0209,  0.0149,
         0.0224, -0.0348,  0.0137,  0.0121,  0.0267, -0.0163,  0.0373, -0.0229,
         0.0038,  0.0209, -0.0292, -0.0084,  0.0150,  0.0434,  0.0153, -0.0121,
        -0.0235

In [58]:
for i in net.mse_loss.parameters():
    print(i)

58不会有任何输出

In [59]:
x = getattr(net, 'fc1')
print(x)

Linear(in_features=400, out_features=120, bias=True)


In [61]:
print('enc_{}'.format(2))

enc_2


In [69]:
import torch
# pool of square window of size=3, stride=2
m = nn.MaxPool2d(3, stride=2)
# pool of non-square window
m = nn.MaxPool2d((3, 2), stride=(2, 1))
input = torch.randn(20, 16, 50, 32)
output = m(input)

In [70]:
print(output.shape)

torch.Size([20, 16, 24, 31])


In [72]:
m = nn.ConvTranspose2d(16, 33, 3, stride=2)
# non-square kernels and unequal stride and with padding
m = nn.ConvTranspose2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2))
input = torch.randn(20, 16, 50, 100)
output = m(input)
print(output.shape)
# exact output size can be also specified as an argument
input = torch.randn(1, 16, 12, 12)
downsample = nn.Conv2d(16, 16, 3, stride=2, padding=1)
upsample = nn.ConvTranspose2d(16, 16, 3, stride=2, padding=1)
h = downsample(input)
print(h.shape)
output = upsample(h, output_size=input.size())
print(output.shape)

torch.Size([20, 33, 93, 100])
torch.Size([1, 16, 6, 6])
torch.Size([1, 16, 12, 12])


In [1]:
from torchvision import models
vgg = models.resnet101()
print(vgg)

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [4]:
print(list(vgg.parameters()))

[Parameter containing:
tensor([[[[-0.0208, -0.0246, -0.0320],
          [ 0.0148,  0.0246, -0.0226],
          [ 0.0889,  0.0624,  0.0663]],

         [[-0.0084,  0.0167,  0.0881],
          [-0.0121, -0.0774,  0.0165],
          [ 0.0707,  0.0438, -0.0114]],

         [[-0.0036,  0.0247, -0.0421],
          [-0.0192, -0.0283,  0.0206],
          [ 0.0775,  0.0185,  0.0646]]],


        [[[-0.0120,  0.0403,  0.0776],
          [ 0.0363, -0.0113,  0.0691],
          [ 0.0455,  0.0472,  0.0209]],

         [[ 0.0148, -0.0292, -0.0266],
          [ 0.0799,  0.0076, -0.0200],
          [-0.0043,  0.0839,  0.0377]],

         [[-0.0237,  0.0241, -0.0035],
          [-0.0829, -0.0196,  0.0291],
          [ 0.0746,  0.0482,  0.0502]]],


        [[[-0.0289, -0.0330, -0.0714],
          [ 0.0083,  0.0221,  0.0173],
          [-0.0403,  0.0664, -0.0437]],

         [[ 0.0630, -0.0167,  0.0679],
          [-0.0080,  0.0497, -0.0496],
          [-0.0334, -0.0621,  0.0083]],

         [[ 0.0522, -

In [8]:
import torch.nn as nn
x = vgg.features[0:2]
net_x = nn.Sequential(*x)
print(net_x)

Sequential(
  (0): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
  )
)
